[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
